on: push

jobs:
    backup:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - run: |
              git pull --unshallow
              echo '${{secrets.KEY}}' > key
              chmod 400 key
              git -c core.sshCommand='ssh -i key -o StrictHostKeyChecking=no' push -f git@bitbucket.org:chaowenguo/${GITHUB_REPOSITORY#*/}
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 18.x
        - run: curl https://bitbucket.org/chaowenguo/common/raw/main/version.js | node --input-type=module
        - uses: actions/setup-node@main
          with:
              node-version: ${{env.JS}}
        - run: |
              echo '${{secrets.KEY}}' > key
              chmod 400 key
              docker login -u chaowenguo -p ${{secrets.DOCKER}}
              git -c core.sshCommand='ssh -i key -o StrictHostKeyChecking=no' clone git@bitbucket.org:chaowenguo/key keykey
              cp -r keykey/certs/* web
              rm -rf keykey
              curl https://bitbucket.org/chaowenguo/common/raw/main/package.json > web/package.json
              npm install --prefix web koa koa-body @koa/cors pg ioredis
              docker build -t chaowenguo/koa web
              docker push chaowenguo/koa
              curl https://bitbucket.org/chaowenguo/common/raw/main/package.json > ingress/package.json
              npm install --prefix ingress koa koa-http2-proxy
              docker build -t chaowenguo/ingress ingress
              docker push chaowenguo/ingress
              curl https://bitbucket.org/chaowenguo/common/raw/main/package.json > chat/package.json
              npm install --prefix chat koa ws
              docker build -t chaowenguo/chat:koa chat
              docker push chaowenguo/chat:koa
              ips=$(curl https://bitbucket.org/chaowenguo/server/raw/main/server.json | sed -e s/,/\ /g -e s/[][\"]//g)
              array=($ips)
              ssh -o StrictHostKeyChecking=no -i key ubuntu@${array[0]} 'sudo docker stop $(sudo docker container ls -q)
              sudo docker system prune -af
              sudo rm -rf /var/lib/cockroach/data
              sudo docker network create backend
              sudo docker run -d --name cockroach --net backend -p 26257:26257 -v ~/certs:/certs:ro -v /var/lib/cockroach/data:/cockroach/cockroach-data --restart always cockroachdb/cockroach start --certs-dir /certs --advertise-addr $(curl https://ifconfig.me) --join $(echo '$ips' | sed s/\ /,/g)
              sudo docker run -d --name redis --net backend -p 6379:6379 -p 16379:16379 redis --cluster-enabled yes --masterauth ${{secrets.PASSWORD}} --requirepass ${{secrets.PASSWORD}}
              sudo docker run -d --name web --net backend -e password=${{secrets.PASSWORD}} chaowenguo/koa
              sudo docker run -d --name chat --net backend chaowenguo/chat:koa
              sudo docker run -d --name ingress --net backend -p 443:443 -v /etc/letsencrypt/live/chaowenguo.eu.org:/encrypt:ro chaowenguo/ingress'
              #sudo docker run -d --name zookeeper -e ZOO_MY_ID=1 -e ZOO_SERVERS="server.1=0.0.0.0:2888:3888;2181 server.2=${ips[1]}:2888:3888;2181 server.3=${ips[2]}:2888:3888;2181" -p 2888:2888 -p 3888:3888 -p 2181:2181 zookeeper
    clean:
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://bitbucket.org/chaowenguo/common/raw/main/clean.py | python - ${{secrets.GITHUB_TOKEN}}             
