on:
    push:
    schedule:
    - cron: '0 1 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - run: curl https://${GITHUB_REPOSITORY%/*}.github.io/common/version.js | node --input-type=module
        - uses: actions/setup-node@main
          with:
              node-version: ${{env.JS}}
        - run: |
              #git fetch --unshallow origin
              #git push https://chaowenguo:HL798820y+@gitlab.com/chaowenGUO/koa.git
              #git push https://chaowenguo:HL798820y+@bitbucket.org/chaowenguo/koa.git
              docker login -u chaowenguo -p ${{secrets.DOCKER}}
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > web/package.json
              npm install --prefix web koa koa-body @koa/cors pg ioredis
              docker build -t chaowenguo/koa web
              docker push chaowenguo/koa
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > ingress/package.json
              npm install --prefix ingress koa koa-http2-proxy
              docker build -t chaowenguo/ingress ingress
              docker push chaowenguo/ingress
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > chat/package.json
              npm install --prefix chat koa ws
              docker build -t chaowenguo/chat:koa chat
              docker push chaowenguo/chat:koa
              curl https://${{secrets.GITHUB}}@raw.githubusercontent.com/chaowenGUO/server/main/key > key
              chmod 400 key
              ssh -o StrictHostKeyChecking=no -i key ubuntu@155.248.192.4 'sudo docker network create backend;
              sudo docker run -d --name redis --network backend redis;
              sudo docker run -d --name web --network backend chaowenguo/koa;
              sudo docker run -d --name chat --network backend chaowenguo/chat:koa;
              sudo docker run -d --name ingress --network backend -p 443:443 -v /etc/letsencrypt/live/chaowenguo.eu.org:/encrypt:ro chaowenguo/ingress'
    clean:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 1 * * *'
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/clean.py | python - ${{secrets.GITHUB_TOKEN}}              
