on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - run: |
              docker login -u chaowenguo -p ${{secrets.DOCKER}}
              npm install koa koa-body @koa/cors pg ioredis
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > package.json
              docker build -t chaowenguo/koa .
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > chat/package.json
              docker push chaowenguo/koa:chat chat
