on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - run: |
              #git fetch --unshallow origin
              #git push https://chaowenguo:HL798820y+@gitlab.com/chaowenGUO/koa.git
              #git push https://chaowenguo:HL798820y+@bitbucket.org/chaowenguo/koa.git
              docker login -u chaowenguo -p ${{secrets.DOCKER}}
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > package.json
              npm install koa koa-body @koa/cors pg ioredis
              docker build -t chaowenguo/koa .
              docker push chaowenguo/koa
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > chat/package.json
              npm install --prefix chat koa chat
              docker build -t chaowenguo/koa:chat chat
              docker push chaowenguo/koa:chat
              echo ${{secrets.EUSERV}} > euserv.key
              ssh -i euserv.key root@2a02:0180:0006:0001:0000:0000:0000:3142 'docker network create --ipv6 --subnet fd10::/64 backend;
              docker run -d --name redis --network backend redis;
              docker run -d --name web --network backend chaowenguo/koa;
              docker run -d --name chat --network backend chaowenguo/chat:koa;
              docker run -d --name nginx --network backend -p 443:443 -v /etc/letsencrypt/live/chaowenguo.eu.org:/encrypt:ro chaowenguo/nginx'
